/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CopingCategory = { 'SelfCare' : null } |
  { 'Relationships' : null } |
  { 'Sleep' : null } |
  { 'HotFlashes' : null } |
  { 'EmotionalRegulation' : null } |
  { 'Work' : null } |
  { 'Focus' : null } |
  { 'BrainFog' : null } |
  { 'Anxiety' : null };
export interface CopingMechanism {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'hasEvidence' : boolean,
  'notes' : string,
  'category' : CopingCategory,
  'isHolistic' : boolean,
}
export interface DailyCheckIn {
  'id' : bigint,
  'focus' : bigint,
  'hotFlashSeverity' : bigint,
  'sleepQuality' : bigint,
  'irritability' : bigint,
  'anxiety' : bigint,
  'date' : Time,
  'mood' : bigint,
  'notes' : [] | [string],
  'energy' : bigint,
}
export interface JournalEntry {
  'id' : bigint,
  'date' : Time,
  'entry' : string,
  'prompt' : [] | [string],
}
export interface SavedItem {
  'id' : bigint,
  'referenceId' : bigint,
  'itemType' : SavedItemType,
}
export type SavedItemType = { 'CopingMechanism' : null } |
  { 'Topic' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategoryToSaved' : ActorMethod<[Principal, bigint, bigint], undefined>,
  'addCopingMechanismToSaved' : ActorMethod<
    [Principal, bigint, bigint],
    undefined
  >,
  'addDailyCheckIn' : ActorMethod<[DailyCheckIn], undefined>,
  'addJournalEntry' : ActorMethod<[JournalEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCopingMechanisms' : ActorMethod<[], Array<CopingMechanism>>,
  'getCopingMechanismsByCategory' : ActorMethod<
    [CopingCategory],
    Array<CopingMechanism>
  >,
  'getDailyCheckIns' : ActorMethod<[Principal], Array<DailyCheckIn>>,
  'getJournalEntries' : ActorMethod<[Principal], Array<JournalEntry>>,
  'getPrompts' : ActorMethod<[], Array<string>>,
  'getSavedItems' : ActorMethod<[Principal], Array<SavedItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];