/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const DailyCheckIn = IDL.Record({
  'id' : IDL.Nat,
  'focus' : IDL.Nat,
  'hotFlashSeverity' : IDL.Nat,
  'sleepQuality' : IDL.Nat,
  'irritability' : IDL.Nat,
  'anxiety' : IDL.Nat,
  'date' : Time,
  'mood' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'energy' : IDL.Nat,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'entry' : IDL.Text,
  'prompt' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CopingCategory = IDL.Variant({
  'SelfCare' : IDL.Null,
  'Relationships' : IDL.Null,
  'Sleep' : IDL.Null,
  'HotFlashes' : IDL.Null,
  'EmotionalRegulation' : IDL.Null,
  'Work' : IDL.Null,
  'Focus' : IDL.Null,
  'BrainFog' : IDL.Null,
  'Anxiety' : IDL.Null,
});
export const CopingMechanism = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'hasEvidence' : IDL.Bool,
  'notes' : IDL.Text,
  'category' : CopingCategory,
  'isHolistic' : IDL.Bool,
});
export const SavedItemType = IDL.Variant({
  'CopingMechanism' : IDL.Null,
  'Topic' : IDL.Null,
});
export const SavedItem = IDL.Record({
  'id' : IDL.Nat,
  'referenceId' : IDL.Nat,
  'itemType' : SavedItemType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategoryToSaved' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Nat], [], []),
  'addCopingMechanismToSaved' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addDailyCheckIn' : IDL.Func([DailyCheckIn], [], []),
  'addJournalEntry' : IDL.Func([JournalEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCopingMechanisms' : IDL.Func([], [IDL.Vec(CopingMechanism)], ['query']),
  'getCopingMechanismsByCategory' : IDL.Func(
      [CopingCategory],
      [IDL.Vec(CopingMechanism)],
      ['query'],
    ),
  'getDailyCheckIns' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DailyCheckIn)],
      ['query'],
    ),
  'getJournalEntries' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'getPrompts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSavedItems' : IDL.Func([IDL.Principal], [IDL.Vec(SavedItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const DailyCheckIn = IDL.Record({
    'id' : IDL.Nat,
    'focus' : IDL.Nat,
    'hotFlashSeverity' : IDL.Nat,
    'sleepQuality' : IDL.Nat,
    'irritability' : IDL.Nat,
    'anxiety' : IDL.Nat,
    'date' : Time,
    'mood' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'energy' : IDL.Nat,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'entry' : IDL.Text,
    'prompt' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CopingCategory = IDL.Variant({
    'SelfCare' : IDL.Null,
    'Relationships' : IDL.Null,
    'Sleep' : IDL.Null,
    'HotFlashes' : IDL.Null,
    'EmotionalRegulation' : IDL.Null,
    'Work' : IDL.Null,
    'Focus' : IDL.Null,
    'BrainFog' : IDL.Null,
    'Anxiety' : IDL.Null,
  });
  const CopingMechanism = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'hasEvidence' : IDL.Bool,
    'notes' : IDL.Text,
    'category' : CopingCategory,
    'isHolistic' : IDL.Bool,
  });
  const SavedItemType = IDL.Variant({
    'CopingMechanism' : IDL.Null,
    'Topic' : IDL.Null,
  });
  const SavedItem = IDL.Record({
    'id' : IDL.Nat,
    'referenceId' : IDL.Nat,
    'itemType' : SavedItemType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategoryToSaved' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Nat], [], []),
    'addCopingMechanismToSaved' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addDailyCheckIn' : IDL.Func([DailyCheckIn], [], []),
    'addJournalEntry' : IDL.Func([JournalEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCopingMechanisms' : IDL.Func([], [IDL.Vec(CopingMechanism)], ['query']),
    'getCopingMechanismsByCategory' : IDL.Func(
        [CopingCategory],
        [IDL.Vec(CopingMechanism)],
        ['query'],
      ),
    'getDailyCheckIns' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DailyCheckIn)],
        ['query'],
      ),
    'getJournalEntries' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getPrompts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSavedItems' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SavedItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };