/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface JournalEntry {
    id: bigint;
    date: Time;
    entry: string;
    prompt?: string;
}
export interface DailyCheckIn {
    id: bigint;
    focus: bigint;
    hotFlashSeverity: bigint;
    sleepQuality: bigint;
    irritability: bigint;
    anxiety: bigint;
    date: Time;
    mood: bigint;
    notes?: string;
    energy: bigint;
}
export interface CopingMechanism {
    id: bigint;
    title: string;
    description: string;
    hasEvidence: boolean;
    notes: string;
    category: CopingCategory;
    isHolistic: boolean;
}
export interface SavedItem {
    id: bigint;
    referenceId: bigint;
    itemType: SavedItemType;
}
export interface UserProfile {
    name: string;
}
export enum CopingCategory {
    SelfCare = "SelfCare",
    Relationships = "Relationships",
    Sleep = "Sleep",
    HotFlashes = "HotFlashes",
    EmotionalRegulation = "EmotionalRegulation",
    Work = "Work",
    Focus = "Focus",
    BrainFog = "BrainFog",
    Anxiety = "Anxiety"
}
export enum SavedItemType {
    CopingMechanism = "CopingMechanism",
    Topic = "Topic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCategoryToSaved(user: Principal, itemId: bigint, categoryId: bigint): Promise<void>;
    addCopingMechanismToSaved(user: Principal, itemId: bigint, mechanismId: bigint): Promise<void>;
    addDailyCheckIn(checkIn: DailyCheckIn): Promise<void>;
    addJournalEntry(entry: JournalEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCopingMechanisms(): Promise<Array<CopingMechanism>>;
    getCopingMechanismsByCategory(category: CopingCategory): Promise<Array<CopingMechanism>>;
    getDailyCheckIns(user: Principal): Promise<Array<DailyCheckIn>>;
    getJournalEntries(user: Principal): Promise<Array<JournalEntry>>;
    getPrompts(): Promise<Array<string>>;
    getSavedItems(user: Principal): Promise<Array<SavedItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { CopingCategory as _CopingCategory, CopingMechanism as _CopingMechanism, DailyCheckIn as _DailyCheckIn, JournalEntry as _JournalEntry, SavedItem as _SavedItem, SavedItemType as _SavedItemType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCategoryToSaved(arg0: Principal, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategoryToSaved(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategoryToSaved(arg0, arg1, arg2);
            return result;
        }
    }
    async addCopingMechanismToSaved(arg0: Principal, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCopingMechanismToSaved(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCopingMechanismToSaved(arg0, arg1, arg2);
            return result;
        }
    }
    async addDailyCheckIn(arg0: DailyCheckIn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyCheckIn(to_candid_DailyCheckIn_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyCheckIn(to_candid_DailyCheckIn_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addJournalEntry(arg0: JournalEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(to_candid_JournalEntry_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(to_candid_JournalEntry_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCopingMechanisms(): Promise<Array<CopingMechanism>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCopingMechanisms();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCopingMechanisms();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCopingMechanismsByCategory(arg0: CopingCategory): Promise<Array<CopingMechanism>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCopingMechanismsByCategory(to_candid_CopingCategory_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCopingMechanismsByCategory(to_candid_CopingCategory_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyCheckIns(arg0: Principal): Promise<Array<DailyCheckIn>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyCheckIns(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyCheckIns(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalEntries(arg0: Principal): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrompts(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrompts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrompts();
            return result;
        }
    }
    async getSavedItems(arg0: Principal): Promise<Array<SavedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedItems(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedItems(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_CopingCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CopingCategory): CopingCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_CopingMechanism_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CopingMechanism): CopingMechanism {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_DailyCheckIn_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyCheckIn): DailyCheckIn {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_JournalEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalEntry): JournalEntry {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SavedItemType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SavedItemType): SavedItemType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_SavedItem_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SavedItem): SavedItem {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    description: string;
    hasEvidence: boolean;
    notes: string;
    category: _CopingCategory;
    isHolistic: boolean;
}): {
    id: bigint;
    title: string;
    description: string;
    hasEvidence: boolean;
    notes: string;
    category: CopingCategory;
    isHolistic: boolean;
} {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        hasEvidence: value.hasEvidence,
        notes: value.notes,
        category: from_candid_CopingCategory_n13(_uploadFile, _downloadFile, value.category),
        isHolistic: value.isHolistic
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    focus: bigint;
    hotFlashSeverity: bigint;
    sleepQuality: bigint;
    irritability: bigint;
    anxiety: bigint;
    date: _Time;
    mood: bigint;
    notes: [] | [string];
    energy: bigint;
}): {
    id: bigint;
    focus: bigint;
    hotFlashSeverity: bigint;
    sleepQuality: bigint;
    irritability: bigint;
    anxiety: bigint;
    date: Time;
    mood: bigint;
    notes?: string;
    energy: bigint;
} {
    return {
        id: value.id,
        focus: value.focus,
        hotFlashSeverity: value.hotFlashSeverity,
        sleepQuality: value.sleepQuality,
        irritability: value.irritability,
        anxiety: value.anxiety,
        date: value.date,
        mood: value.mood,
        notes: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.notes)),
        energy: value.energy
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    entry: string;
    prompt: [] | [string];
}): {
    id: bigint;
    date: Time;
    entry: string;
    prompt?: string;
} {
    return {
        id: value.id,
        date: value.date,
        entry: value.entry,
        prompt: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.prompt))
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    referenceId: bigint;
    itemType: _SavedItemType;
}): {
    id: bigint;
    referenceId: bigint;
    itemType: SavedItemType;
} {
    return {
        id: value.id,
        referenceId: value.referenceId,
        itemType: from_candid_SavedItemType_n27(_uploadFile, _downloadFile, value.itemType)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SelfCare: null;
} | {
    Relationships: null;
} | {
    Sleep: null;
} | {
    HotFlashes: null;
} | {
    EmotionalRegulation: null;
} | {
    Work: null;
} | {
    Focus: null;
} | {
    BrainFog: null;
} | {
    Anxiety: null;
}): CopingCategory {
    return "SelfCare" in value ? CopingCategory.SelfCare : "Relationships" in value ? CopingCategory.Relationships : "Sleep" in value ? CopingCategory.Sleep : "HotFlashes" in value ? CopingCategory.HotFlashes : "EmotionalRegulation" in value ? CopingCategory.EmotionalRegulation : "Work" in value ? CopingCategory.Work : "Focus" in value ? CopingCategory.Focus : "BrainFog" in value ? CopingCategory.BrainFog : "Anxiety" in value ? CopingCategory.Anxiety : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CopingMechanism: null;
} | {
    Topic: null;
}): SavedItemType {
    return "CopingMechanism" in value ? SavedItemType.CopingMechanism : "Topic" in value ? SavedItemType.Topic : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CopingMechanism>): Array<CopingMechanism> {
    return value.map((x)=>from_candid_CopingMechanism_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyCheckIn>): Array<DailyCheckIn> {
    return value.map((x)=>from_candid_DailyCheckIn_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JournalEntry>): Array<JournalEntry> {
    return value.map((x)=>from_candid_JournalEntry_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SavedItem>): Array<SavedItem> {
    return value.map((x)=>from_candid_SavedItem_n25(_uploadFile, _downloadFile, x));
}
function to_candid_CopingCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CopingCategory): _CopingCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_DailyCheckIn_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyCheckIn): _DailyCheckIn {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_JournalEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JournalEntry): _JournalEntry {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    focus: bigint;
    hotFlashSeverity: bigint;
    sleepQuality: bigint;
    irritability: bigint;
    anxiety: bigint;
    date: Time;
    mood: bigint;
    notes?: string;
    energy: bigint;
}): {
    id: bigint;
    focus: bigint;
    hotFlashSeverity: bigint;
    sleepQuality: bigint;
    irritability: bigint;
    anxiety: bigint;
    date: _Time;
    mood: bigint;
    notes: [] | [string];
    energy: bigint;
} {
    return {
        id: value.id,
        focus: value.focus,
        hotFlashSeverity: value.hotFlashSeverity,
        sleepQuality: value.sleepQuality,
        irritability: value.irritability,
        anxiety: value.anxiety,
        date: value.date,
        mood: value.mood,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        energy: value.energy
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: Time;
    entry: string;
    prompt?: string;
}): {
    id: bigint;
    date: _Time;
    entry: string;
    prompt: [] | [string];
} {
    return {
        id: value.id,
        date: value.date,
        entry: value.entry,
        prompt: value.prompt ? candid_some(value.prompt) : candid_none()
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CopingCategory): {
    SelfCare: null;
} | {
    Relationships: null;
} | {
    Sleep: null;
} | {
    HotFlashes: null;
} | {
    EmotionalRegulation: null;
} | {
    Work: null;
} | {
    Focus: null;
} | {
    BrainFog: null;
} | {
    Anxiety: null;
} {
    return value == CopingCategory.SelfCare ? {
        SelfCare: null
    } : value == CopingCategory.Relationships ? {
        Relationships: null
    } : value == CopingCategory.Sleep ? {
        Sleep: null
    } : value == CopingCategory.HotFlashes ? {
        HotFlashes: null
    } : value == CopingCategory.EmotionalRegulation ? {
        EmotionalRegulation: null
    } : value == CopingCategory.Work ? {
        Work: null
    } : value == CopingCategory.Focus ? {
        Focus: null
    } : value == CopingCategory.BrainFog ? {
        BrainFog: null
    } : value == CopingCategory.Anxiety ? {
        Anxiety: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
